from selenium.webdriver.common.by import By

class UrbanRoutesLocators:
    from_field = (By.ID, 'from')
    to_field = (By.ID, 'to')
    button_round = (By.CLASS_NAME, "button round")
    button_comfort_xpath = (By.XPATH, '//*[@id="root"]/div/div[3]/div[3]/div[2]/div[1]/div[5]')
    set_phone_number = (By.CLASS_NAME, 'np-text')
    input_phone_number = (By.ID, 'phone')
    number = (By.XPATH, '//*[@id="phone"]')
    button_next_xpath = (By.XPATH, '//*[text()="Siguiente"]')
    input_code = (By.ID, 'code')
    button_confirm_xpath = (By.XPATH, '//*[text()="Confirmar"]')
    select_taxi_xpath = (By.XPATH, '//*[@id="root"]/div/div[3]/div[3]/div[1]/div[3]/div[1]/button')
    button_payment_method = (By.CLASS_NAME, "pp-button")
    button_add_card = (By.CLASS_NAME, "pp-plus")
    set_credit_card = (By.CLASS_NAME, 'card-number-input')
    input_credit_card_xpath = (By.XPATH, '//*[@id="number"]')
    input_card_cvv_xpath = (By.XPATH, '//div[@class="card-code-input"]/input[@id="code"]')
    submit_card_xpath = (By.XPATH, '//*[text()="Agregar"]')
    button_close_xpath = (By.XPATH, '//*[@id="root"]/div/div[2]/div[2]/div[1]/button')
    input_comment_css = (By.CSS_SELECTOR, "#comment")
    checkbox_bket_scrvs_xpath = (By.XPATH, '//*[@id="root"]/div/div[3]/div[3]/div[2]/div[2]/div[4]/div[2]/div[1]/div/div[2]/div/span')
    checkbox_slide_bket_scrvs_xpath = (By.XPATH, '//*[@id="root"]/div/div[3]/div[3]/div[2]/div[2]/div[4]/div[2]/div[1]/div/div[2]/div/input')
    counter_ice_cream = (By.CLASS_NAME, "counter-plus")
    counter_ice_cream_value_2 = (By.XPATH,'//*[@id="root"]/div/div[3]/div[3]/div[2]/div[2]/div[4]/div[2]/div[3]/div/div[2]/div[1]/div/div[2]/div/div[2]')
    button_smart_order = (By.CLASS_NAME, "smart-button-main")
    order_header_title = (By.CLASS_NAME, 'order-header-title')
    modal_order = (By.CLASS_NAME, "order-details")
